name: Code Quality

on:
  workflow_call:
    outputs:
      detekt-passed:
        description: "Whether Detekt checks passed"
        value: ${{ jobs.detekt.outputs.passed }}

jobs:
  detekt:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.detekt.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Detekt
        id: detekt
        run: ./gradlew detekt

      - name: Upload Detekt reports
        if: always() && steps.detekt.conclusion != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: detekt-reports-${{ github.run_id }}
          path: |
            **/build/reports/detekt/detekt.html
            **/build/reports/detekt/detekt.xml
            **/build/reports/detekt/detekt.md
            **/build/reports/detekt/detekt.txt
            build/reports/problems/problems-report.html
          if-no-files-found: ignore
          retention-days: 7
